import { useEffect, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { api, errorMessage } from '../api/client'
import type { Job } from '../api/types'
import { useAuth } from '../auth/AuthContext'

const blank={title:'',company:'',location:'',department:'',employmentType:'Full-time',description:'',requirements:'',minSalary:'',maxSalary:'',stages:'Applied\nScreen\nInterview\nOffer'}
export function RecruiterJobsPage(){const{user}=useAuth();const[jobs,setJobs]=useState<Job[]>([]);const[show,setShow]=useState(false);const[form,setForm]=useState(blank);const[error,setError]=useState('');const[loading,setLoading]=useState(true)
  async function load(){setLoading(true);try{setJobs((await api.get<Job[]>('/recruiter/jobs')).data)}catch(cause){setError(errorMessage(cause))}finally{setLoading(false)}} useEffect(()=>{void load()},[])
  const update=(key:string,value:string)=>setForm(current=>({...current,[key]:value}))
  async function create(event:FormEvent){event.preventDefault();setError('');try{await api.post('/recruiter/jobs',{...form,minSalary:form.minSalary?Number(form.minSalary):null,maxSalary:form.maxSalary?Number(form.maxSalary):null});setForm(blank);setShow(false);await load()}catch(cause){setError(errorMessage(cause))}}
  return <><section className="dashboard-hero"><div className="container dashboard-title"><div><p className="eyebrow">Recruiter console</p><h1>Welcome, {user?.fullName}</h1><p>Publish roles, review candidates, and move hiring conversations forward.</p></div><button className="button secondary" onClick={()=>setShow(!show)}>{show?'Close form':'Post a new job'}</button></div></section>
  <section className="overlap section"><div className="container panel">{show&&<form className="form card" onSubmit={create}><div className="form-row"><div className="field"><label>Job title</label><input required value={form.title} onChange={e=>update('title',e.target.value)}/></div><div className="field"><label>Company</label><input required value={form.company} onChange={e=>update('company',e.target.value)}/></div></div><div className="form-row"><div className="field"><label>Location</label><input required value={form.location} onChange={e=>update('location',e.target.value)}/></div><div className="field"><label>Department</label><input value={form.department} onChange={e=>update('department',e.target.value)}/></div></div><div className="field"><label>Employment type</label><select value={form.employmentType} onChange={e=>update('employmentType',e.target.value)}><option>Full-time</option><option>Part-time</option><option>Contract</option><option>Internship</option></select></div><div className="field"><label>Description</label><textarea required rows={5} value={form.description} onChange={e=>update('description',e.target.value)}/></div><div className="field"><label>Requirements</label><textarea rows={4} value={form.requirements} onChange={e=>update('requirements',e.target.value)}/></div><div className="form-row"><div className="field"><label>Minimum salary</label><input type="number" value={form.minSalary} onChange={e=>update('minSalary',e.target.value)}/></div><div className="field"><label>Maximum salary</label><input type="number" value={form.maxSalary} onChange={e=>update('maxSalary',e.target.value)}/></div></div><div className="field"><label>Pipeline stages (one per line)</label><textarea rows={4} value={form.stages} onChange={e=>update('stages',e.target.value)}/></div><button className="button">Publish job</button></form>}
    <div className="section-title" style={{marginTop:show?32:0}}><div><h2>Open roles</h2><p className="muted small">You currently have {jobs.length} posting{jobs.length===1?'':'s'}.</p></div></div>{error&&<p className="error">{error}</p>}{loading?<div className="page-state">Loading roles…</div>:jobs.length===0?<div className="empty">No jobs posted yet. Create your first role and start collecting applications.</div>:<div className="list">{jobs.map(job=><div className="list-item" key={job.id}><div><h3>{job.title}</h3><p className="muted small">{job.location} · {job.employmentType} · Posted {new Date(job.createdAt).toLocaleDateString()}</p></div><div><span className="small muted">{job.applicationsCount} applicants</span> <Link className="button compact" to={`/recruiter/jobs/${job.id}`}>View pipeline</Link></div></div>)}</div>}
  </div></section></>}

